version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - cd docs && poetry export --dev -f requirements.txt > requirements.txt && cd ..

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
