version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - gfortran
    - libopenblas-dev
    - liblapack-dev
  tools:
    python: "3.10"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - poetry install

sphinx:
   configuration: docs/conf.py
